name: Ubuntu 24.04 GUI RDP Tailscale

on:
  workflow_dispatch:

jobs:
    rdp-vps:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Password for Runner
      run: |
        echo "runner:vpspassword123" | sudo chpasswd

    - name: Connect to Tailscale Network
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
        args: --ssh

    - name: Install Desktop Environment & XRDP
      run: |
        sudo apt update
        # Install XFCE Desktop dan XRDP server
        sudo DEBIAN_FRONTEND=noninteractive apt install -y xfce4 xfce4-goodies xrdp
        
        # Konfigurasi XRDP agar menggunakan XFCE
        echo "startxfce4" > ~/.xsession
        sudo sed -i 's/port=3389/port=3389/g' /etc/xrdp/xrdp.ini
        
        # Izinkan user runner mengakses xrdp dan restart service
        sudo usermod -aG sudo runner
        sudo systemctl restart xrdp

    - name: Keep RDP Alive
      run: |
        echo "=========================================="
        echo "RDP Ubuntu 24.04 Berhasil Dijalankan!"
        echo "Buka aplikasi Remote Desktop (RDP Client)"
        echo "Masukkan IP Tailscale dan login:"
        echo "Username: runner"
        echo "Password: vpspassword123"
        echo "=========================================="
        
        sleep 21600
